/* Autogenerated bridge — do not edit by hand.
 *
 * R's build system requires at least one C source file in src/ to produce a
 * DLL.  This file provides that, and bridges R's standard package init
 * entrypoint (R_init_essierust) to the symbol generated by the
 * extendr_module! macro in Rust (R_init_essierust_extendr).
 */

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

/* Declared in the Rust static library, generated by extendr_module! */
void R_init_essierust_extendr(void *dll);

/* R calls this when it loads the DLL (useDynLib triggers the lookup).
 * attribute_visible is omitted: on Windows all exported symbols are
 * visible by default, so the macro is unnecessary and causes parse
 * errors under -std=gnu2x (Rtools 4.5). */
void R_init_essierust(void *dll) {
    R_init_essierust_extendr(dll);
}
