##' Fit an Essie model (Rust-accelerated, gamma movement kernel)
##'
##' Drop-in replacement for the pure-R \code{essie} function.  The likelihood
##' computation (\code{logpk}) stays in R; both the movement kernel
##' (\code{logbk}) and the forward/backward accumulation loop are executed
##' entirely in compiled Rust via \code{\link{step_gamma}}.
##'
##' @param model  A model structure generated by \code{essieThresholdModel}.
##'   Must contain \code{beta} (gamma shape/rate vector) and \code{time}.
##' @param grid   A raster object defining the grid.
##' @param epsilon1  Likelihood tolerance.
##' @param epsilon2  Transition-probability tolerance.
##' @param verbose   Report progress to the console?
##' @return A list with elements \code{grid}, \code{time}, and \code{lattice}.
##' @importFrom utils flush.console
##' @importFrom raster ncell values
##' @export
essie <- function(model, grid,
                  epsilon1 = 1e-3, epsilon2 = 1e-16,
                  verbose  = interactive()) {

  normalize <- function(x) {
    s <- sum(x)
    if (s == 0) x else x / s
  }

  n     <- length(model$time)
  pts   <- lonlatFromCell(grid, seq_len(ncell(grid)))
  fixed <- integer(n)
  fixed[model$fixed] <- cellFromLonLat(grid, model$x0[model$fixed, ])

  # Time steps (hours) — dt[k] is the gap between observation k and k+1.
  dt <- diff(as.numeric(model$time) / 3600)

  # Precompute the gamma log-normalizer: a constant across all steps.
  # log f(x) = (shape-1)*log(x) - rate*x + log_norm
  log_norm <- model$beta[1] * log(model$beta[2]) - lgamma(model$beta[1])

  ## ------------------------------------------------------------------
  ## Build lattice: one entry per time step.
  ## logpk involves solar-position calculations; stays in R.
  ## ------------------------------------------------------------------
  cs <- seq_len(ncell(grid))[values(grid) != 0]

  lattice <- lapply(seq_len(n), function(k) {
    if (fixed[k] != 0) {
      list(cs = fixed[k], ps = 1)
    } else {
      logps <- model$logpk(k, pts[cs, , drop = FALSE])
      keep  <- logps > log(epsilon1) + max(logps)
      list(cs = cs[keep], ps = normalize(exp(logps[keep])))
    }
  })

  ## ------------------------------------------------------------------
  ## Forward sweep
  ##
  ## step_gamma receives matrices column-major (as R stores them), so
  ## as.double(xs) = [lon_1, ..., lon_n, lat_1, ..., lat_n].
  ## No transpose is needed.
  ## ------------------------------------------------------------------
  if (verbose) { cat("Fwd ", sprintf("%6d", 1)); flush.console() }

  xs <- pts[lattice[[1]]$cs, , drop = FALSE]
  as <- lattice[[1]]$as <- lattice[[1]]$ps

  for (k in 2:n) {
    if (verbose) { cat("\b\b\b\b\b\b"); cat(sprintf("%6d", k)); flush.console() }

    xs0 <- xs
    xs  <- pts[lattice[[k]]$cs, , drop = FALSE]

    # Transition from step k-1 to k uses dt[k-1].
    as <- step_gamma(
      as.double(xs0),       # source locs (column-major)
      as.double(xs),        # dest locs   (column-major)
      as,                   # source weights
      lattice[[k]]$ps,      # dest likelihoods
      dt[k - 1],            # hours between obs k-1 and k
      model$beta[1],        # gamma shape
      model$beta[2],        # gamma rate
      log_norm,
      epsilon2
    )
    lattice[[k]]$as <- as
  }

  ## ------------------------------------------------------------------
  ## Backward sweep
  ##
  ## Distance is symmetric, so step_gamma serves both directions.
  ## Transition from step k+1 to k uses dt[k].
  ## ------------------------------------------------------------------
  if (verbose) { cat("\nBwd ", sprintf("%6d", n)); flush.console() }

  xs <- pts[lattice[[n]]$cs, , drop = FALSE]
  bs <- lattice[[n]]$bs <- lattice[[n]]$ps

  for (k in (n - 1):1) {
    if (verbose) { cat("\b\b\b\b\b\b"); cat(sprintf("%6d", k)); flush.console() }

    xs0 <- xs
    xs  <- pts[lattice[[k]]$cs, , drop = FALSE]

    # xs0 = next-step locs, xs = current-step locs; dt[k] is the gap between them.
    bs <- step_gamma(
      as.double(xs0),
      as.double(xs),
      bs,
      lattice[[k]]$ps,
      dt[k],
      model$beta[1],
      model$beta[2],
      log_norm,
      epsilon2
    )
    lattice[[k]]$bs <- bs
  }

  list(grid = grid, time = model$time, lattice = lattice)
}
