# Generated by extendr: Do not edit by hand.
#
# Regenerate with:
#   rextendr::document()
# after any change to the Rust source.

#' @docType package
#' @usage NULL
#' @useDynLib essierust, .registration = TRUE
NULL

#' One Essie sweep step — gamma movement kernel (Rust)
#'
#' Computes a single forward or backward sweep step using the TwilightFree
#' gamma movement model entirely in Rust.  Eliminates R-level \code{logbk}
#' callbacks from the inner loop.
#'
#' @param xs0_flat  Source locations, column-major flat vector, length \code{2 * n_src}.
#'   Pass with \code{as.double(xs0_matrix)} directly from R — no transpose needed.
#' @param xs_flat   Destination locations, column-major, length \code{2 * n_dest}.
#' @param weights   Source weights (unthresholded), length \code{n_src}.
#' @param ps        Destination likelihoods from \code{logpk}, length \code{n_dest}.
#' @param dt        Time step between the two frames (hours).
#' @param beta_shape  Gamma shape parameter.
#' @param beta_rate   Gamma rate parameter.
#' @param log_norm    Precomputed \code{beta_shape * log(beta_rate) - lgamma(beta_shape)}.
#' @param epsilon2    Threshold: sources with weight below \code{epsilon2 * max(weights)}
#'   are skipped.
#' @return Normalised numeric vector of length \code{n_dest}.
#' @export
step_gamma <- function(xs0_flat, xs_flat, weights, ps,
                       dt, beta_shape, beta_rate, log_norm, epsilon2) {
  .Call(wrap__step_gamma,
        xs0_flat, xs_flat, weights, ps,
        dt, beta_shape, beta_rate, log_norm, epsilon2)
}

#' Weighted accumulation kernel — generic (Rust)
#'
#' Use when the movement model is \strong{not} the TwilightFree gamma kernel.
#' The R driver pre-computes the log-transition matrix via \code{model$logbk}
#' and passes it here.
#'
#' @param weights   Active source weights (already thresholded), length \code{n_active}.
#' @param logb_flat Log-transition matrix \strong{row-major}, length
#'   \code{n_active * n_dest}.
#' @param ps        Destination likelihoods, length \code{n_dest}.
#' @return Normalised numeric vector of length \code{n_dest}.
#' @export
accumulate_normalize <- function(weights, logb_flat, ps) {
  .Call(wrap__accumulate_normalize, weights, logb_flat, ps)
}
